version: '3.5'

services:
  solbroker:
    image: solace-pubsub-standard:$PUBSUB_TAG
    hostname: $PUBSUB_HOSTNAME
    env_file:
      - ./solace.env
    ports:
      - "2222:2222"
      - "8080:8080"
      - "55003:55003"
      - "55443:55443"
      - "55445:55445"
      - "55555:55555"
      - "55556:55556"
      - "5672:5672"
      - "5550:5550"
      - "8008:8008"
    shm_size: 2g
    ulimits:
      memlock: -1
      nofile: 
        soft: 2448
        hard: 42192
